[source]
    source_dir = "/home/www/"
    target_dir = "/root/"
    delete_dir = "/tmp/watch_file"

[destination]
    ssh_ip = "47.24.10.249"
    ssh_port = "22333"
    ssh_user = "www"
    ssh_identify = "～/.ssh/dientify.pem"

[command]
    completed_cmd = "touch /root/b.text"

[replace_rule]
    sed_rule = "'s/1e15849033-laa84/1149b49065-rku24/g'"